name: Test Dispatch

on:
  repository_dispatch:
    types: [event-1]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Confirm Dispatch Triggered
      run: echo "Dispatch event triggered successfully!"
